name: Build ilwispy

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v4
    - name: install python
      run: |
           apt-get update
           apt-get -y install wget
           wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
           sh ./Miniconda3-latest-Linux-x86_64.sh -b
           /github/home/miniconda3/bin/conda init
           . /github/home/.bashrc
           conda create -y --name custompython python=${{ matrix.python-version }}
           conda activate custompython
    - name: install dependencies
      run: |
           apt-get -y install build-essential
           DEBIAN_FRONTEND=noninteractive apt-get -y install tzdata
           apt-get -y install qt5-qmake
           apt-get -y install qtbase5-dev
           # apt-get -y install python3-dev
           apt-get -y install libquazip5-dev
           apt-get -y install libboost-dev
           apt-get -y install libgdal-dev
           apt-get -y install libgsl-dev
           apt-get -y install libeigen3-dev
           apt-get -y install libnetcdf-c++4-dev
           apt-get -y install swig3.0
    - name: install python packages
      run: |
           . /github/home/.bashrc
           conda activate custompython
           python3 -m pip install --upgrade pip
           python3 -m pip install wheel setuptools twine
    - name: patch
      run: |
           . /github/home/.bashrc
           conda activate custompython
           python3 patch_pythonapi_linux.py
           ln -s /usr/include/quazip5/ ilwis4connector/quazip
    - name: configure
      run: |
           qmake -o Makefile.core core.pro
           qmake -o Makefile.baseoperations baseoperations.pro
           qmake -o Makefile.featureoperations featureoperations.pro
           qmake -o Makefile.gdalconnector gdalconnector.pro
           qmake -o Makefile.hydroflow hydroflow.pro
           qmake -o Makefile.ilwis3connector ilwis3connector.pro
           qmake -o Makefile.ilwis4connector ilwis4connector.pro
           qmake -o Makefile.ilwisscript ilwisscript.pro
           qmake -o Makefile.internalconnector internalconnector.pro
           qmake -o Makefile.netcdfconnector netcdfconnector.pro
           qmake -o Makefile.opencv opencv.pro
           qmake -o Makefile.projectionimplproj4 projectionimplproj4.pro
           qmake -o Makefile.pythonapi pythonapi.pro
           qmake -o Makefile.rasteroperations rasteroperations.pro
           qmake -o Makefile.streamconnector streamconnector.pro
           qmake -o Makefile ilwisobjects.pro
    - name: make
      run: |
           . /github/home/.bashrc
           conda activate custompython
           make -f Makefile
    - name: publish
      env:
           TWINE_USERNAME: __token__
           TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
           . /github/home/.bashrc
           conda activate custompython
           cd ../output/gccx64_/release/python_whl
           python3 -m twine upload --repository testpypi *.whl --verbose
